# Generated by Django 4.2.1 on 2023-06-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Esse campo precisará estar marcado para apágina ser exibida publicamente'),
        ),
    ]
